#!/usr/bin/env bash
# Transfers a file from our client to a server and accepting 4 parameters

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning parameters to variables

FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

# Transfer file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"

# Check if scp command was successful
if [ $? -eq 0 ]; then
    echo "File transfer completed successfully."
else
    echo "File transfer failed."
fi
