#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# Creates a symbolic link, restarts then terminates the first process
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"

