#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# Creates a symbolic link
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart Nginx
service nginx start
# Terminates first process os nginx
kill "$(pgrep 'nginx' | head -1)”
