#!/usr/bin/env bash
# SSH client configuration

Host *
   passwordAuthentication no
   IdentityFile ~/.ssh/school
   SendEnv LANG LC_*
   HashKNownHosts yes
   GSSAPIAuthentication yes
   GSSSAPIDelegateCredentials no
